### ISSUE TITLE
PHPUnit dependency is not a dev dependency

### ISSUE THREAD

**Issue by JensJI** [konsulting/dusk-standalone#5]
Thank you for a great package!

I have had a issue because your composer.json adds PHPUnit as a production dependency.

That means, that when I install your package (because I wanna consume it, not test it), it adds a specific version of PHPUnit.
When I wanna test and develop my own project I now have a conflict in my dev-environment with the PHPUnit version, as your package has it installed as a normal dependency.

Could it be moved to "require-dev" section so that this problem will be eliminated?

Thanks again for your work! :-)

**Comment by Keoghan** [comment]
Hi @JensJI, thanks for looking at the package :) I'll try to take a look at this in the next day or so. 

I wonder if your issue is better solved by using a different specification for the allowed PHP Unit versions in composer.json (e.g. allow the version you are attempting to use in `require` section) rather than moving it to `require-dev`. Or, you could use a different version that matches the PHPUnit version you need?

Are you using the package as a dependency inside your application?

Thanks!

Keoghan

**Comment by JensJI** [comment]
Hi @Keoghan .

I have solved it temporary by downgrading my PHP Unit, so that it matches the one in your package.

As I understand it, we cannot pull 2 different versions of the same package into my composer's vendor-directory.
So when your package pulls a specific PHP Unit, I cannot pull another version of PHP Unit for my own test-suite.

I am using the package as a dev-dependency, because it is part of my test-suite :-)

**Comment by Keoghan** [comment]
Thank @JensJI which version of PHPUnit do you want to use in your project - I have not added the most recent versions of Dusk yet, so perhaps this is the best solution? :)

**Comment by JensJI** [comment]
So I think I am a little confused. But I get it now.
I thought that you just used phpunit as a dev dependency to test your own package, but of course it is a very central part of the package and therefor cannot just be moved. And it's your class I extend so it has to be compatible!

Sorry for bothering you and thank you for your work! :-)

**Comment by Keoghan** [comment]
Awesome, it's no problem at all - I am glad it is useful! :)
